In [4]:
import numpy as np

In [8]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
x.mean(axis=(0))

array([2., 3.])

In [13]:
x.min()

1

In [14]:
np.shape(x)

(2, 2)

In [15]:
np.shape(x.min())

()

In [16]:
x.min().shape

()

In [17]:
x.std(axis=0)

array([1., 1.])

In [26]:
x=np.array([[[1,2,3],
             [4,5,6]],
            [[1,2,3],
              [4,5,6]]])
x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [31]:
x.mean(axis=(-2,-1))

array([3.5, 3.5])

In [35]:
(x.min()).shape

()

In [38]:
x.std(axis=(0,1,2))

1.707825127659933

In [39]:
np.sum(x, axis=(0,1))

array([10, 14, 18])